#cloud-config

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - ca-certificates
  - nginx

runcmd:
  - systemctl start nginx
  - systemctl enable nginx

write_files:
  - path: /etc/nginx/sites-available/default
    permissions: 0644
    encoding: b64
    content: ${nginx_conf_text}
